### Create a new User with a credentials username:password
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "John Doe",
  "username": "johs",
  "password": "123456"
}


### Authenticated a  User with a credentials username:password
POST http://localhost:3333/sessions/credentials
Content-Type: application/json

{
  "username": "johs",
  "password": "123456"
}

### Get the user profile 


GET http://localhost:3333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjMxODNhOS05YmQwLTQyZjMtYTI0NS1iZjkxNTc1M2JkOWIiLCJpYXQiOjE3MTk1MTE3MTV9.Z458k-xa8YWNd6ViUChK728cVYTqMSjTKmkEGY4XBcw