### Create a new User with a credentials username:password
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Maria Doe",
  "username": "Maria",
  "password": "123456"
}


### Authenticated a  User with a credentials username:password
POST http://localhost:3333/sessions/credentials
Content-Type: application/json

{
  "username": "Maria",
  "password": "123456"
}

### Authenticated a  User with a Google Access Token
POST http://localhost:3333/sessions/google
Content-Type: application/json

{
  "code": "4/0ATx3LY4axBaPdEuaKxoSMXhyjwhkvu2xhseYr37XGaXXkmChFTZHHBiMhNJmasMHTVTJ5w"
}


### Get the user profile 


GET http://localhost:3333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZGYwM2IwMi1iNGRhLTQwNWMtOTAwZC03NTc5MTU5ZDQyZTEiLCJpYXQiOjE3MTk2MjcyNjgsImV4cCI6MTcxOTYyNzg2OH0.pJ4lNMu8moa83uYsukPajrnDWgqvjrwrDszaVg0n8W8